# Generated by Django 4.2.24 on 2025-09-10 22:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('user', 'url')},
        ),
    ]
